package com.saveheart.security.enums;

public enum EnvironmentApiKey {
    LOCAL("THISISAVERYLONGANDSOMETHINGSOMETHINGHARDSECRETSALTWHATEVERITISBLABLABLABLABLABLABLALOOKSGOODIGUESS"),
    LOCAL2("THISISAVERYLONGANDSOMETHINGSOMETHINGHARDSECRETSALTWHATEVERITISBLABLABLABLATHISISSECONDONEBLABLABLALOOKSGOODIGUESS"),
    PROD("THISISAVERYLONGANDSOMETHINGSOMETHINGHARDSECRETSALTWHATEVERITISBLABLABLABLABLABLABLALOOKSGOODIGUESS"),
    PROD2("THISISAVERYLONGANDSOMETHINGSOMETHINGHARDSECRETSALTWHATEVERITISBLABLABLABLATHISISSECONDONEBLABLABLALOOKSGOODIGUESS"),
    ;
    private String value;

	public String getValue() {
		return value;
	}

	/**
	 * @param value
	 */
	private EnvironmentApiKey(String value) {
		this.value = value;
	}
    
    
}
